### ISSUE TITLE
Error: Cannot find module 'redis'

### ISSUE THREAD

**Issue by eronquillo** [ipbc-dev/ipbc-pool#3]
Hi, I'm receiving an error after running "node init.js"

~/ipbc-pool# node init.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'redis'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/ipbc-pool/init.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by ipbc-dev** [comment]
install redis pls.

**Comment by ipbc-dev** [comment]
Did you run "npm install" before running init.js?
