### ISSUE TITLE
Failed to parse block Error

### ISSUE THREAD

**Issue by CoFix** [ipbc-dev/ipbc-pool#6]
On a fresh IPBC pool setup, i can this error in pool log once a miner will conntect to the pool:

Error: Failed to parse block
at Error (native)
at Object.nextBlob (/home/pool/pool/lib/pool.js:177:23)
at Object.getJob (/home/pool/pool/lib/pool.js:346:41)
at handleMinerMethod (/home/pool/pool/lib/pool.js:651:28)
at handleMessage (/home/pool/pool/lib/pool.js:789:13)
at Socket. (/home/pool/pool/lib/pool.js:843:25)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)

What is the problem? How can i fix it?

**Comment by ipbc-dev** [comment]
What was the IPBC daemon showing during this?
