### ISSUE TITLE
linux printf error 

### ISSUE THREAD

**Issue by 772687713** [ipbc-dev/ipbc-pool#8]
i'm cry to build bittube pool by myself,but it's failed ,linux printf :
Error: bind EADDRINUSE
    at errnoException (net.js:905:11)
    at net.js:1085:30
    at Object.11:4 (cluster.js:594:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at child_process.js:396:7
    at process.handleConversion.net.Native.got (child_process.js:91:7)

My first step ./bittubed -rpc-bind-port=32349 
       Second step ./simplewallet --wallet-file=wallte.bin --pass=123 '''--daemon-port=32348''' '''--rpc-bind-port=32349'''
        third step Configuration pool config.json and pagejson
        at last i try to node inite.js

**Comment by ipbc-dev** [comment]
Error: bind EADDRINUSE 

you have already someting using this port, change the port or shutdown the other service
